name: Validate Kubernetes Resources

on:
  push:
    branches:
      - task-6-3
      - dev
      - main
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  validate:
    defaults:
      run:
        working-directory: "tasks/task-6-3/dev"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Check Kubernetes 
      run: kubeconform -ignore-missing-schemas .
    
  kubeconform:
    runs-on: ubuntu-latest
    steps:
      - name: login to Github Packages
        run: echo "${{ github.token }}" | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin
      - uses: actions/checkout@v2
      - uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          entrypoint: '/kubeconform'
          args: "-summary -output json kubeconfigs/"
