name: Validate Kubernetes Resources

on:
  push:
    branches:
      - task-6-3
      - dev
      - main
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

env:
  CONFTEST_VERSION: 0.51.0

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install conftest
      run: |
        wget -O - 'https://github.com/open-policy-agent/conftest/releases/download/v${{ env.CONFTEST_VERSION }}/conftest_${{ env.CONFTEST_VERSION }}_Linux_x86_64.tar.gz' | tar zxvf -
        ./conftest --version
    - name: Run conftest
      run: ./conftest test tasks/task-6-3
  # validate:
  #   defaults:
  #     run:
  #       working-directory: "tasks/task-6-3/dev"
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
        
  #   - name: Check Kubernetes 
  #     run: kubeconform -ignore-missing-schemas .
    
  # kubeconform:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: login to Github Packages
  #       run: echo "${{ github.token }}" | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin
  #     - uses: actions/checkout@v2
  #     - uses: docker://ghcr.io/yannh/kubeconform:latest
  #       with:
  #         entrypoint: '/kubeconform'
  #         args: "-summary -output json kubeconfigs/"
